name: Deploy Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      #code is not a server; it is in a repo that is hosted on a machine that GitHub owns, runner is isolated from it so it must be found
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
  deploy:
    # cmd that lets workflow know that the deploy job should run sequentially
    needs: test
    # each job gets its own runner, its own VM that is isolated from other runner's
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deploy
        run: echo "Deploying ..."
